
# ============================================================
#01_two_body_problem.py
# ============================================================
import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

print("RUNNING:")


# ============================================================
# 1. Physical constants
# ============================================================

mu = 3.986004418e14   # = GM, unities m^3/s^2, Earth's gravitational parameter
R_earth = 6371e3      # m, Earth radius


# ============================================================
# 2. User options
# ============================================================

orbit_type = "custom"
# Available options:
#   "circular"
#   "elliptical"
#   "escape"
#   "custom"

h = 100e3  # m, initial altitude above Earth's surface

# Used only if orbit_type == "custom"
custom_speed_factor = 0.9
# The custom initial speed will be:
# v0 = custom_speed_factor * v_circular


# ============================================================
# 3. Initial conditions
# ============================================================

# Initial position: spacecraft located on the positive x-axis
r0 = np.array([R_earth + h, 0.0])
r0_norm = np.linalg.norm(r0)

# Reference speeds at the initial radius
v_circular = np.sqrt(mu / r0_norm)
v_escape = np.sqrt(2 * mu / r0_norm)

# Select initial tangential velocity
if orbit_type == "circular":
    speed = v_circular
elif orbit_type == "elliptical":
    speed = 1.2 * v_circular
elif orbit_type == "escape":
    speed = 1.05 * v_escape
elif orbit_type == "custom":
    speed = custom_speed_factor * v_circular
else:
    raise ValueError(
        "Invalid orbit_type. Choose from: "
        "'circular', 'elliptical', 'escape', 'custom'."
    )

v0 = np.array([0.0, speed])

# Full initial state vector: [x, y, vx, vy]
y0 = np.hstack([r0, v0])

# For reduced 2-body problem (rocket mass m ~ 0) 
# energy and angular momentum are "specific" ones: Joules/kg and (m^2/s) per kg
specific_energy = 0.5 * np.dot(v0, v0) - mu / r0_norm
specific_angular_momentum = r0[0] * v0[1] - r0[1] * v0[0]
eccentricity = np.sqrt(1 + 2 * specific_energy * specific_angular_momentum**2 / mu**2)

# ============================================================
# 4. Informative output
# ============================================================

specific_energy = 0.5 * np.dot(v0, v0) - mu / r0_norm

if np.isclose(specific_energy, 0.0, atol=1e-6):
    orbit_nature = "parabolic"
elif specific_energy < 0:
    orbit_nature = "bound"
else:
    orbit_nature = "unbound"

print("Selected orbit type:", orbit_type)
print("Initial position vector r0 (m):", r0)
print("Initial distance from Earth's center (km):", r0_norm / 1e3)
print("Initial velocity vector v0 (m/s):", v0)
print("Initial speed |v0| (km/s):", np.linalg.norm(v0) / 1e3)
print("Circular speed at this altitude (km/s):", v_circular / 1e3)
print("Escape speed at this altitude (km/s):", v_escape / 1e3)
print("Specific mechanical energy (J/kg):", specific_energy)
print("Expected orbit nature:", orbit_nature)
print("Speed ratio v/v_circular:", speed / v_circular)
print("Speed ratio v/v_escape:", speed / v_escape)
print("Specific mechanical energy (J/kg):", specific_energy)
print("Specific angular momentum (m^2/s):", specific_angular_momentum)
print("Orbital eccentricity:", eccentricity)

# ============================================================
# 5. Equations of motion
# ============================================================

def two_body_equations(t, y):
    """
    Equations of motion for a test body in a 2D Newtonian
    gravitational field generated by Earth.

    Parameters
    ----------
    t : float
        Time (s). Required by solve_ivp, although the system
        does not depend explicitly on time.
    y : array_like
        State vector [x, y, vx, vy].

    Returns
    -------
    dydt : ndarray
        Time derivative of the state vector:
        [vx, vy, ax, ay]
    """
    r = y[0:2]
    v = y[2:4]

    r_norm = np.linalg.norm(r)
    a = -mu * r / r_norm**3

    return np.hstack([v, a])


# ============================================================
# 6. Event: impact with Earth
# ============================================================

def hit_earth_event(t, y):
    """
    Event function that becomes zero when the spacecraft reaches
    Earth's surface.
    """
    r = y[0:2]
    return np.linalg.norm(r) - R_earth

hit_earth_event.terminal = True
hit_earth_event.direction = -1


# ============================================================
# 7. Integration interval
# ============================================================

# Characteristic orbital period for a circular orbit at the initial radius
T_circular = 2 * np.pi * np.sqrt(r0_norm**3 / mu)

if orbit_type == "escape":
    t_final = 1.5 * T_circular
else:
    t_final = 3.0 * T_circular

t_span = (0.0, t_final)
t_eval = np.linspace(t_span[0], t_span[1], 3000)


# ============================================================
# 8. Numerical integration
# ============================================================

sol = solve_ivp(
    two_body_equations,
    t_span,
    y0,
    t_eval=t_eval,
    events=hit_earth_event,
    rtol=1e-6,
    atol=1e-8
)

if not sol.success:
    print("Warning: integration was not fully successful.")
    print("Solver message:", sol.message)


# ============================================================
# 9. Extract solution
# ============================================================

x_m = sol.y[0]
y_m = sol.y[1]
vx_m = sol.y[2]
vy_m = sol.y[3]

r_m = np.sqrt(x_m**2 + y_m**2)
v_m = np.sqrt(vx_m**2 + vy_m**2)

x = x_m / 1e3
y = y_m / 1e3
r_km = r_m / 1e3

r_min = r_km.min()
r_max = r_km.max()

print("Minimum distance from Earth's center (km):", r_min)
print("Maximum distance from Earth's center (km):", r_max)

if sol.t_events[0].size > 0:
    impact_time = sol.t_events[0][0]
    print("The spacecraft hits Earth.")
    print("Impact time (s):", impact_time)
    print("Impact time (min):", impact_time / 60)
else:
    print("No impact detected during the integration interval.")


# ============================================================
# 10. Plot
# ============================================================

fig, ax = plt.subplots(figsize=(7, 7))

# Trajectory
ax.plot(x, y, label="Trajectory", linewidth=2)

# Initial point
ax.plot(x[0], y[0], "o", label="Initial position")

# Earth as a filled circle
earth = plt.Circle((0, 0), R_earth / 1e3, fill=True, alpha=0.3, label="Earth")
ax.add_patch(earth)

# Formatting
ax.set_aspect("equal", adjustable="box")
ax.grid(True)
ax.set_xlabel("x (km)")
ax.set_ylabel("y (km)")
ax.set_title(f"Two-body problem under Newtonian gravity ({orbit_type} case)")
ax.legend()

# Automatic square limits with a small margin
pad = 0.08
xmin, xmax = x.min(), x.max()
ymin, ymax = y.min(), y.max()

# Include Earth in the limits
xmin = min(xmin, -R_earth / 1e3)
xmax = max(xmax,  R_earth / 1e3)
ymin = min(ymin, -R_earth / 1e3)
ymax = max(ymax,  R_earth / 1e3)

cx = 0.5 * (xmin + xmax)
cy = 0.5 * (ymin + ymax)
half = 0.5 * max(xmax - xmin, ymax - ymin)
half *= (1 + pad)

ax.set_xlim(cx - half, cx + half)
ax.set_ylim(cy - half, cy + half)

plt.show()
